### ISSUE TITLE
Video Support

### ISSUE THREAD

**Issue by jnpetersen** [insanj/ContentTableViewController#1]
Could you add video support to be able to play videos within the app, both small or pushed fullscreen?

**Comment by insanj** [comment]
Great idea! What format would the video be supplied in, `NSData`? `NSURL`?

**Comment by jnpetersen** [comment]
`NSURL` would be best I think, but either way should work.

**Comment by insanj** [comment]
Implemented starting in 598d344aa6cbb712de0312ed52ceb50a904fb534, now in Cocoapods version 1.3.1! I haven't extensively tested this, but it's a rather transparent API and I hope to battle test it in the coming days.
